--------------------------------------------------------
--  File created - Wednesday-September-12-2018   
--------------------------------------------------------
@E:\Projects\GitHub\Life-Insurance\TYPES\SYS_PLSQL_59B8E432_307_1.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\SYS_PLSQL_59B8E432_384_1.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\SYS_PLSQL_59B8E432_DUMMY_1.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_01_AM_USR_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_01_AM_USR_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_BRCH_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_BRCH_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_BRH_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_BRH_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_CLS_N_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_CLS_N_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_CLS_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_CLS_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_DEPT_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_DEPT_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_DIVN_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_DIVN_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_PRD_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_PRD_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_PROD_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_PROD_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_CT_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_LOS_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_POL_LOS_TAB.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_TF_ROW.sql
@E:\Projects\GitHub\Life-Insurance\TYPES\T_TF_TAB.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_BENF.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_INFO_TMP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_QUST.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_CUS_TP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_PRD_INFO.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_PRD_RT.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_PRD_TERM.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_PYMT_FEQ.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_QUST_INFO.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_CUS.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_CUS_DOC.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_DOC.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_DOC_TP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_POL_MEM.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_POL_NO.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_20_UW_PROD_DOC.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_CUS_ACT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_CATG.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_MAP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_NTR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_TP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_ACT_TYPE.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_COMP.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_CST_CNTR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_DEPT.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_FSCL_YR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_JV_MST.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_JV_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_LOC.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_MSTR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_GL_VCHR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_MODE_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_PYMT_COMM.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_PYMT_COMM_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_70_TRAN_SRCE.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_99_SSU_AUD.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_99_SSU_PRIV.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_99_SSU_RLE.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\SEQUENCES\S_99_SSU_USR_RLE.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\APEX_TEAM_DEV_FILES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_EMAILS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_EMAIL_AFFECTS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_EMAIL_TEMPLATES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_ERRORS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_ERROR_LOOKUP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_FEEDBACK.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_NOTIFICATIONS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_USERS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HM_USER_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\HTMLDB_PLAN_TABLE.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_APEX2JRXML_TEMPLATES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_FONTS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_LOGGING.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_NLS_PARAMETERS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_REPORT_DEFINITIONS.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_REPORT_IMAGES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_REPORT_PARAM.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_RESOURCE_ENTRIES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\JRXML_RESOURCE_FILES.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\SYS_EXPORT_SCHEMA_01.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_BENF.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_INFO_TMP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_QUST.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_CUS_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_PRD_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_PRD_RT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_PRD_TERM.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_PRD_TERM_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_PYMT_FEQ.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_QUST_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_APR_STA.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_CUS_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_CUS_IMG.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_DOC_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_POL_END_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_POL_MEM.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_POL_STA.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_PRD_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_PROD_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_20_UW_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_CUS_ACT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_CATG.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_LVL.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_MAP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_NTR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_TP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_ACT_TYPE.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_COMP.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_CST_CNTR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_DEPT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_FSCL_YR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_JV_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_LOC.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_MSTR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_VCHR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_GL_VCHR_NTR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_MODE_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_PYMT_COMM.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_PYMT_COMM_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_70_TRAN_SRCE.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_APP_MDL.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_AUD.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_LOG.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_PMV.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_PRIV.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_PWD_PRF.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_RLE.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_STA.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\TABLES\T_99_SSU_USR_RLE.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\R_20_UW_POL_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\R_70_CUS_ACT_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\R_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\R_70_PYMT_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_ALL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_BENF.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_BRK_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_QUST.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_CUS_TP.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_DASH_01.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PRD_INFO.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PRD_RT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PRD_TERM.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PRD_TERM_LOV.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PRD_TERM_TP.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_PYMT_FEQ.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_QUST_INFO.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_UW_CUS_DOC.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_UW_CUS_DOC_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_UW_POL_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_20_UW_POL_MEM.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_BRK_PYMT_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_CUS_ACT_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_CUS_ACT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_CUS_ACT_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_ALL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_CATG.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_CTL_ALL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_LVL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_MAP.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_NTR.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_ACT_TP.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_COMP.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_DEPT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_JV_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_JV_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_LOC.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_RCPT_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_GL_VCHR.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_MODE_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_PYMT_COMM.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_PYMT_COMM_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_PYMT_COMM_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_70_PYMT_TRAN_DTL.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_AUD.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_LOG.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_PMV.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_PRIV.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_PWD_PRF.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_RLE.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\VIEWS\V_99_SSU_USR_RLE.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_JV_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_LVL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_CUS_DOC_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_POL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_LOC_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_DOC_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_AFFECTS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_POL_PK_2.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_TYPE2_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_NOTIFICATIONS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_PYMT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_CUS_INFO_TMP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_MODE_PYMT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAILS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_DOC_TP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_PYMT_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_PMV_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_VCHR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_USR_RLE_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRF_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_CUS_ACT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_TYPE_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_PYMT_COMM_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_PROD_DOC_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_PRD_TERM_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_AUD_TRL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_BRK_PYMT_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JAT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_PRIV_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_APR_STA_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_ERRORS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_FEEDBACK_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_NTR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_JV_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_USERS_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_TEMPLATES_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_PRD_RT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_CTL_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_MSTR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_CUS_ACT_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_APP_MDL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRS_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_CUS_BRK_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_USERS_USERNAME_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\TABLE1_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_USR_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_COMP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_PYMT_COMM_TRAN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRD_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_PYMT_FEQ_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_TEMPLATES_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_ERRORS_I1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_PWD_PRF_CON.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_VCHR_NTR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_CATG_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRD_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_PMV_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_QUST_INFO_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_STA_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRI_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_MAP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRI_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_CUS_TP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_PRD_INFO_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_CST_CNTR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_AFFECTS_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_USR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_PREFERENCES_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_ERROR_LOOKUP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_POL_END_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_ACT_CTL_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_AFFECTS_IDX2.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_POL_MEM_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRF_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_PRD_TERM_TP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_FSCL_YR_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRN_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAIL_AFFECTS_IDX1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_ERROR_LOOKUP_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_99_SSU_PWD_PRF_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JAT_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_USER_PREFERENCES_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_EMAILS_IDX1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_TRAN_SRCE_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRR_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_CUS_QUST_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\JRN_UK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_DEPT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_CUS_IMG_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\HM_PREFERENCES_NAME_IDX.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_PRD_TP_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_CUS_ACT_UK1.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_20_UW_POL_STA_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_CUS_RCPT_PK.sql
@E:\Projects\GitHub\Life-Insurance\INDEXES\T_70_GL_RCPT_UK1.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\APEX_TEAM_DEV_FILES_BIU.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_ERRORS.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_FEEDBACK.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_NOTIFICATIONS.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_USERS.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\BIU_HM_USER_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\HM_EMAILS_BIU.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\HM_EMAIL_AFFECTS_BIU.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\HM_EMAIL_TEMPLATES_BIU.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TRG_JRI_BRUI.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TRG_JRR_BRUI.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_CUS_BENF.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_CUS_QUST.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_CUS_TP.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_PRD_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_PRD_RT.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_PRD_TERM.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_PYMT_FEQ.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_QUST_INFO.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_CUS_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_DOC_TP.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_POL_MEM.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_20_UW_PROD_DOC.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_CUS_ACT_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_CUS_ACT_TRAN_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_CATG.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_MAP.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_NTR.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_TP.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_ACT_TYPE.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_COMP.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_CST_CNTR_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_DEPT.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_FSCL_YR.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_JV_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_LOC.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_MSTR_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_RCPT_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_TRAN_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_GL_VCHR_.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_MODE_PYMNT.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_PYMT_COMM.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_PYMT_COMM_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_70_TRAN_SRCE.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_99_SSU_AUD.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_99_SSU_PRIV.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_99_SSU_RLE.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\TRIGGERS\TR_99_SSU_USR_RLE.sql
@E:\Projects\GitHub\Life-Insurance\PROCEDURES\SHOW_HTML_FROM_URL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\HM_EMAIL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\HM_FEEDBACK_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\HM_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\HM_SEARCH_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_20_CUS_STP.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_20_PRM_CAL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_99_SSU_AUTH.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_99_SSU_ERR.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_99_SSU_PMV.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGES\PK_99_SSU_VAL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\HM_EMAIL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\HM_FEEDBACK_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\HM_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\HM_SEARCH_FW.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_20_CUS_STP.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_20_PRM_CAL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_99_SSU_AUTH.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_99_SSU_ERR.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_99_SSU_PMV.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\PACKAGE_BODIES\PK_99_SSU_VAL.sql
@E:\Projects\GitHub\Life-Insurance\FUNCTIONS\ORACLE_URL_ENCODE.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_PWD_PRF.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_FONTS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_QUST.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_CUS_ACT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_COMP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_LOGGING.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_PRD_RT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_DOC_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\APEX_TEAM_DEV_FILES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_PRD_INFO.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_TRAN_SRCE.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_USR_RLE.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_NLS_PARAMETERS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_BRK.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_CUS_DOC.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_PRIV.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_PRD_TERM.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_CST_CNTR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_RLE.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_NOTIFICATIONS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_POL_MEM.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_RCPT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_PRD_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_NTR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_AUD.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_REPORT_DEFINITIONS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_DEPT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_REPORT_IMAGES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_VCHR_NTR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_QUST_INFO.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_JV.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_LOC.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_VCHR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_APP_MDL.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_EMAIL_AFFECTS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_ERROR_LOOKUP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_POL_END_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_POL_STA.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_CTL.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_JV_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_ERRORS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_PROD_DOC.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_PYMT_COMM_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_APR_STA.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_USR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_EMAILS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_RESOURCE_FILES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_STA.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_APEX2JRXML_TEMPLATES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_MAP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_INFO_TMP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_PRD_TERM_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_POL.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_BRK_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\JRXML_RESOURCE_ENTRIES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_CATG.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_TYPE.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_INFO.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_USERS.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_TP.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_MSTR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_CUS_IMG.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_CUS_BENF.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_UW_DOC.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_CUS_ACT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_FSCL_YR.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_FEEDBACK.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_99_SSU_PMV.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_USER_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_20_PYMT_FEQ.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_GL_ACT_LVL.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_MODE_PYMT.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\HM_EMAIL_TEMPLATES.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_PYMT_COMM.sql
@E:\Projects\GitHub\Life-Insurance\CONSTRAINTS\T_70_PYMT_TRAN.sql
@E:\Projects\GitHub\Life-Insurance\REF_CONSTRAINTS\HM_EMAILS.sql
@E:\Projects\GitHub\Life-Insurance\REF_CONSTRAINTS\HM_EMAIL_AFFECTS.sql
@E:\Projects\GitHub\Life-Insurance\REF_CONSTRAINTS\HM_USER_PREFERENCES.sql
@E:\Projects\GitHub\Life-Insurance\REF_CONSTRAINTS\JRXML_REPORT_IMAGES.sql
@E:\Projects\GitHub\Life-Insurance\REF_CONSTRAINTS\JRXML_RESOURCE_ENTRIES.sql
