--------------------------------------------------------
--  DDL for Type SYS_PLSQL_59B8E432_307_1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "SYS_PLSQL_59B8E432_307_1" as object (FILTER_SEQUENCE NUMBER,
FILTER_GROUP VARCHAR2(4000 BYTE),
FILTER_DISPLAY VARCHAR2(4000 BYTE),
FILTER_VALUE VARCHAR2(4000 BYTE),
NUMERIC_VALUE NUMBER,
MIN_NUM_VALUE NUMBER,
MAX_NUM_VALUE NUMBER,
MIN_BOUNDARY VARCHAR2(2 BYTE),
MAX_BOUNDARY VARCHAR2(2 BYTE),
DATE_VALUE DATE,
ACTIVE_GROUP VARCHAR2(4000 BYTE),
MATCH_COL VARCHAR2(1 BYTE));

/
