--------------------------------------------------------
--  Constraints for Table APEX$TEAM_DEV_FILES
--------------------------------------------------------

  ALTER TABLE "APEX$TEAM_DEV_FILES" MODIFY ("COMPONENT_ID" NOT NULL ENABLE);
  ALTER TABLE "APEX$TEAM_DEV_FILES" MODIFY ("COMPONENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "APEX$TEAM_DEV_FILES" MODIFY ("FILENAME" NOT NULL ENABLE);
  ALTER TABLE "APEX$TEAM_DEV_FILES" ADD CONSTRAINT "WWV_VALID_ATDF_COMP_TY" CHECK (component_type in ('MILESTONE','FEATURE','BUG','FEEDBACK','TODO')) ENABLE;
  ALTER TABLE "APEX$TEAM_DEV_FILES" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
