--------------------------------------------------------
--  Constraints for Table HM_EMAIL_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "HM_EMAIL_TEMPLATES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_TEMPLATES" MODIFY ("TEMPLATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_TEMPLATES" MODIFY ("FULL_TEMPLATE_HTML" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_TEMPLATES" MODIFY ("TEXT_TEMPLATE" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_TEMPLATES" ADD CONSTRAINT "HM_EMAIL_TEMPLATES_UK" UNIQUE ("TEMPLATE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "HM_EMAIL_TEMPLATES" ADD CONSTRAINT "HM_EMAIL_TEMPLATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
