--------------------------------------------------------
--  Constraints for Table HM_EMAIL_AFFECTS
--------------------------------------------------------

  ALTER TABLE "HM_EMAIL_AFFECTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_AFFECTS" MODIFY ("EMAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_AFFECTS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HM_EMAIL_AFFECTS" ADD CONSTRAINT "HM_EMAIL_AFFECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HM_EMAIL_AFFECTS" ADD CONSTRAINT "HM_EMAIL_AFFECTS_CC1" CHECK (user_opted_out_yn in ('Y','N')) ENABLE;
  ALTER TABLE "HM_EMAIL_AFFECTS" ADD CONSTRAINT "HM_EMAIL_AFFECTS_UK1" UNIQUE ("EMAIL_ID", "USERNAME")
  USING INDEX  ENABLE;
