--------------------------------------------------------
--  Constraints for Table HM_ERROR_LOOKUP
--------------------------------------------------------

  ALTER TABLE "HM_ERROR_LOOKUP" MODIFY ("CONSTRAINT_NAME" NOT NULL ENABLE);
  ALTER TABLE "HM_ERROR_LOOKUP" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "HM_ERROR_LOOKUP" MODIFY ("LANGUAGE_CODE" NOT NULL ENABLE);
  ALTER TABLE "HM_ERROR_LOOKUP" ADD CONSTRAINT "HM_ERROR_LOOKUP_PK" PRIMARY KEY ("CONSTRAINT_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "HM_ERROR_LOOKUP" ADD CONSTRAINT "HM_ERROR_LOOKUP_UK1" UNIQUE ("LANGUAGE_CODE")
  USING INDEX  ENABLE;
