--------------------------------------------------------
--  Constraints for Table HM_NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "HM_NOTIFICATIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HM_NOTIFICATIONS" MODIFY ("NOTIFICATION_NAME" NOT NULL ENABLE);
  ALTER TABLE "HM_NOTIFICATIONS" MODIFY ("NOTIFICATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HM_NOTIFICATIONS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HM_NOTIFICATIONS" MODIFY ("UPDATED_BY" NOT NULL ENABLE);
  ALTER TABLE "HM_NOTIFICATIONS" ADD CONSTRAINT "HM_NOTIFICATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HM_NOTIFICATIONS" ADD CONSTRAINT "HM_NOTIFICATION_TYPE_CK" CHECK (notification_type in ('RED','YELLOW')) ENABLE;
