--------------------------------------------------------
--  Constraints for Table HM_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "HM_PREFERENCES" MODIFY ("IS_REQUIRED_YN" NOT NULL ENABLE);
  ALTER TABLE "HM_PREFERENCES" MODIFY ("DATATYPE" NOT NULL ENABLE);
  ALTER TABLE "HM_PREFERENCES" ADD CONSTRAINT "HM_IS_REQ_CK" CHECK (is_required_yn in ('Y','N')) ENABLE;
  ALTER TABLE "HM_PREFERENCES" ADD CONSTRAINT "HM_DATATYPE_CK" CHECK (datatype in ('TEXT','NUM')) ENABLE;
  ALTER TABLE "HM_PREFERENCES" ADD CONSTRAINT "HM_PREFERENCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
