--------------------------------------------------------
--  Constraints for Table JRXML_RESOURCE_FILES
--------------------------------------------------------

  ALTER TABLE "JRXML_RESOURCE_FILES" MODIFY ("JRR_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_FILES" MODIFY ("JRR_NAME" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_FILES" MODIFY ("JRR_VALID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_FILES" MODIFY ("JRR_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_FILES" ADD CONSTRAINT "JRR_VALID_CK" CHECK (JRR_VALID IN ('Y', 'N')) ENABLE;
  ALTER TABLE "JRXML_RESOURCE_FILES" ADD CONSTRAINT "JRR_PK" PRIMARY KEY ("JRR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_RESOURCE_FILES" ADD CONSTRAINT "JRR_UK" UNIQUE ("JRR_NAME", "JRR_LOCALE")
  USING INDEX  ENABLE;
