--------------------------------------------------------
--  Constraints for Table JRXML_APEX2JRXML_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" MODIFY ("JAT_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" MODIFY ("JAT_NAME" NOT NULL ENABLE);
  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" MODIFY ("JAT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" MODIFY ("JAT_STANDARD" NOT NULL ENABLE);
  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" ADD CONSTRAINT "JAT_PK" PRIMARY KEY ("JAT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_APEX2JRXML_TEMPLATES" ADD CONSTRAINT "JAT_UK" UNIQUE ("JAT_TYPE", "JAT_NAME")
  USING INDEX  ENABLE;
