--------------------------------------------------------
--  Constraints for Table JRXML_NLS_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_LOCALE_LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_NLS_LANGUAGE" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_NLS_TERRITORY" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_NUMERIC_CHARACTERS" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_DEFAULT_DATE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_SHORT_DATE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_MEDIUM_DATE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_LONG_DATE_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_DEFAULT_TIME_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_SHORT_TIME_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_MEDIUM_TIME_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_LONG_TIME_FORMAT" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_DATE_TIME_STRING" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" MODIFY ("JRN_CURRENCY" NOT NULL ENABLE);
  ALTER TABLE "JRXML_NLS_PARAMETERS" ADD CONSTRAINT "JRN_PK" PRIMARY KEY ("JRN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_NLS_PARAMETERS" ADD CONSTRAINT "JRN_UK" UNIQUE ("JRN_LOCALE_LANGUAGE", "JRN_LOCALE_COUNTRY")
  USING INDEX  ENABLE;
