--------------------------------------------------------
--  Constraints for Table JRXML_LOGGING
--------------------------------------------------------

  ALTER TABLE "JRXML_LOGGING" MODIFY ("JRL_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_LOGGING" MODIFY ("JRL_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_LOGGING" MODIFY ("JRL_TIME" NOT NULL ENABLE);
  ALTER TABLE "JRXML_LOGGING" MODIFY ("JRL_TIME_SINCE_LAST_LOG" NOT NULL ENABLE);
  ALTER TABLE "JRXML_LOGGING" ADD CONSTRAINT "JRL_PK" PRIMARY KEY ("JRL_ID")
  USING INDEX  ENABLE;
