--------------------------------------------------------
--  Constraints for Table JRXML_FONTS
--------------------------------------------------------

  ALTER TABLE "JRXML_FONTS" MODIFY ("JRF_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_FONTS" MODIFY ("JRF_NAME" NOT NULL ENABLE);
  ALTER TABLE "JRXML_FONTS" MODIFY ("JRF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "JRXML_FONTS" MODIFY ("JRF_COMPRESS" NOT NULL ENABLE);
  ALTER TABLE "JRXML_FONTS" ADD CONSTRAINT "JRF_UK" UNIQUE ("JRF_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_FONTS" ADD CONSTRAINT "JRF_PK" PRIMARY KEY ("JRF_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_FONTS" ADD CONSTRAINT "JRF_TYPE_CK" CHECK (JRF_TYPE IN ('TTF', 'TTC')) ENABLE;
