--------------------------------------------------------
--  Constraints for Table JRXML_RESOURCE_ENTRIES
--------------------------------------------------------

  ALTER TABLE "JRXML_RESOURCE_ENTRIES" MODIFY ("JRS_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_ENTRIES" MODIFY ("JRS_JRR_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_ENTRIES" MODIFY ("JRS_KEY" NOT NULL ENABLE);
  ALTER TABLE "JRXML_RESOURCE_ENTRIES" ADD CONSTRAINT "JRS_PK" PRIMARY KEY ("JRS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_RESOURCE_ENTRIES" ADD CONSTRAINT "JRS_UK" UNIQUE ("JRS_JRR_ID", "JRS_KEY")
  USING INDEX  ENABLE;
