--------------------------------------------------------
--  Constraints for Table JRXML_REPORT_IMAGES
--------------------------------------------------------

  ALTER TABLE "JRXML_REPORT_IMAGES" MODIFY ("JRI_ID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_REPORT_IMAGES" MODIFY ("JRI_NAME" NOT NULL ENABLE);
  ALTER TABLE "JRXML_REPORT_IMAGES" MODIFY ("JRI_ADLER32_VALID" NOT NULL ENABLE);
  ALTER TABLE "JRXML_REPORT_IMAGES" ADD CONSTRAINT "JRI_UK" UNIQUE ("JRI_JRD_ID", "JRI_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_REPORT_IMAGES" ADD CONSTRAINT "JRI_PK" PRIMARY KEY ("JRI_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "JRXML_REPORT_IMAGES" ADD CONSTRAINT "JRI_ALER32_CK" CHECK (JRI_ADLER32_VALID IN ('Y', 'N')) ENABLE;
