--------------------------------------------------------
--  Constraints for Table T_99_SSU_USR
--------------------------------------------------------

  ALTER TABLE "T_99_SSU_USR" MODIFY ("R_K" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_USR" MODIFY ("USR_ID" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_USR" MODIFY ("UPD_DT" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_USR" MODIFY ("IUS_YN" NOT NULL ENABLE);
  ALTER TABLE "T_99_SSU_USR" ADD CONSTRAINT "T_99_SSU_USR_UK1" UNIQUE ("USR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "T_99_SSU_USR" ADD CONSTRAINT "T_99_SSU_USR_PK" PRIMARY KEY ("R_K")
  USING INDEX  ENABLE;
