--------------------------------------------------------
--  DDL for Table HM_EMAILS
--------------------------------------------------------

  CREATE TABLE "HM_EMAILS" 
   (	"ID" NUMBER, 
	"TEMPLATE_ID" NUMBER, 
	"SUBJECT" VARCHAR2(255), 
	"BODY1_TEXT" VARCHAR2(4000), 
	"TABLE_CONTENT" VARCHAR2(4000), 
	"BODY2_TEXT" VARCHAR2(4000), 
	"ACTION_LABEL" VARCHAR2(70), 
	"ACTION_LINK" VARCHAR2(4000), 
	"CAN_OPT_OUT_YN" VARCHAR2(1) DEFAULT 'Y', 
	"EMAIL_BODY" CLOB, 
	"NBR_EMAILS_SENT" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255)
   ) ;
