--------------------------------------------------------
--  DDL for Table HM_EMAIL_AFFECTS
--------------------------------------------------------

  CREATE TABLE "HM_EMAIL_AFFECTS" 
   (	"ID" NUMBER, 
	"EMAIL_ID" NUMBER, 
	"USERNAME" VARCHAR2(255), 
	"USER_TZ_PREF" VARCHAR2(60), 
	"USER_LANG_CODE" VARCHAR2(10), 
	"USER_OPTED_OUT_YN" VARCHAR2(1), 
	"EMAIL_SENT_ON" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"EMAIL_ERROR" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255)
   ) ;
