--------------------------------------------------------
--  DDL for Table HM_EMAIL_TEMPLATES
--------------------------------------------------------

  CREATE TABLE "HM_EMAIL_TEMPLATES" 
   (	"ID" NUMBER, 
	"TEMPLATE_NAME" VARCHAR2(255), 
	"FULL_TEMPLATE_HTML" CLOB, 
	"TEXT_TEMPLATE" VARCHAR2(4000), 
	"TABLE_OPEN_HTML" VARCHAR2(4000), 
	"TR_HTML" VARCHAR2(4000), 
	"TABLE_CLOSE_HTML" VARCHAR2(4000), 
	"ACTION_BUTTON_HTML" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255)
   ) ;
