--------------------------------------------------------
--  DDL for Table HM_NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "HM_NOTIFICATIONS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"NOTIFICATION_NAME" VARCHAR2(255), 
	"NOTIFICATION_DESCRIPTION" VARCHAR2(4000), 
	"NOTIFICATION_TYPE" VARCHAR2(30), 
	"DISPLAY_SEQUENCE" NUMBER, 
	"DISPLAY_FROM" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"DISPLAY_UNTIL" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) ;
