--------------------------------------------------------
--  DDL for Table HM_PREFERENCES
--------------------------------------------------------

  CREATE TABLE "HM_PREFERENCES" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"PREFERENCE_NAME" VARCHAR2(100), 
	"PREFERENCE_VALUE" VARCHAR2(4000), 
	"IS_REQUIRED_YN" VARCHAR2(1) DEFAULT 'N', 
	"DATATYPE" VARCHAR2(5) DEFAULT 'TEXT', 
	"DESCRIPTION" VARCHAR2(4000), 
	"VALID_VALUES" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255)
   ) ;
