--------------------------------------------------------
--  DDL for Table HM_USERS
--------------------------------------------------------

  CREATE TABLE "HM_USERS" 
   (	"ID" NUMBER, 
	"ROW_VERSION_NUMBER" NUMBER, 
	"EMAIL_ADDRESS" VARCHAR2(255), 
	"USERNAME" VARCHAR2(255), 
	"FIRST_NAME" VARCHAR2(100), 
	"LAST_NAME" VARCHAR2(100), 
	"WORK_PHONE" VARCHAR2(30), 
	"MOBILE_PHONE" VARCHAR2(30), 
	"TITLE" VARCHAR2(255), 
	"ADDRESS" VARCHAR2(4000), 
	"PHOTO_BLOB" BLOB, 
	"PHOTO_NAME" VARCHAR2(512), 
	"PHOTO_MIMETYPE" VARCHAR2(512), 
	"PHOTO_CHARSET" VARCHAR2(512), 
	"PHOTO_LASTUPD" DATE, 
	"NOTE" VARCHAR2(4000), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(255), 
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"UPDATED_BY" VARCHAR2(255)
   ) ;
