--------------------------------------------------------
--  DDL for Table JRXML_NLS_PARAMETERS
--------------------------------------------------------

  CREATE TABLE "JRXML_NLS_PARAMETERS" 
   (	"JRN_ID" NUMBER(38,0), 
	"JRN_LOCALE_LANGUAGE" VARCHAR2(10), 
	"JRN_LOCALE_COUNTRY" VARCHAR2(10), 
	"JRN_NLS_LANGUAGE" VARCHAR2(80), 
	"JRN_NLS_TERRITORY" VARCHAR2(80), 
	"JRN_NUMERIC_CHARACTERS" VARCHAR2(2), 
	"JRN_DEFAULT_DATE_FORMAT" VARCHAR2(80), 
	"JRN_SHORT_DATE_FORMAT" VARCHAR2(80), 
	"JRN_MEDIUM_DATE_FORMAT" VARCHAR2(80), 
	"JRN_LONG_DATE_FORMAT" VARCHAR2(80), 
	"JRN_DEFAULT_TIME_FORMAT" VARCHAR2(80), 
	"JRN_SHORT_TIME_FORMAT" VARCHAR2(80), 
	"JRN_MEDIUM_TIME_FORMAT" VARCHAR2(80), 
	"JRN_LONG_TIME_FORMAT" VARCHAR2(80), 
	"JRN_DATE_TIME_STRING" VARCHAR2(10), 
	"JRN_CURRENCY" VARCHAR2(10)
   ) ;
